### ISSUE TITLE
Add filters support

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-image-tools#19]
Allow to filter files by extension, for example.

**Comment by tatarincev** [comment]
**Functional requirements:**
As Manager, I want to change the default file extensions (file masks)  that the thumbnail-generation task uses for search and generation in the target folder

**Technical requirements:**
Need to extend `ThumbnailTask`  with `Filters` property which would contain the string  represents the comma-separated  File Masks & Wildcards filter  for example: `*.png, *.jpg` 
Add some logic to code  which takes into account this task filters property in the search files operation
In UI extend the task details blade with the new input field (with placeholder text that represents the default file mask)

**Comment by andrey-ciclicci** [comment]
According to [MSDN article](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.image.fromfile?redirectedfrom=MSDN&view=netframework-4.7.2#System_Drawing_Image_FromFile_System_String_) built-in encoders/decoders support only 5 image formats: ".bmp", ".gif", ".jpg", ".png", ".tiff". As described here https://stackoverflow.com/a/10544645 the image masks could be:
Bitmap images: *.bmp
GIF images: *.gif
JPEG images: *.jpg, *.jpeg, *.jpe, *.jif, *.jfif, *.jfi
PNG images: *.png
TIFF images: *.tiff, *.tif

We could add them all as a default filter and solve #20 as well.

**Comment by tatarincev** [comment]
@andrey-ciclicci I totally agree. We do not need to complicate our product with excess UI settings :)

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-module-image-tools/releases/v1.2.1
