### ISSUE TITLE
Process only images

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-image-tools#20]
If I store my images as Git LFS repository, for example, or have unhidden system files, I will receive exception

> Cannot generate thumbnail: http://localhost/admin/assets/catalog/.gitattributes does not have a valid image format

Process only images. Use MIME type to detect them, for example.

**Comment by andrey-ciclicci** [comment]
Solved using default image filtering by extension in #29

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-module-image-tools/releases/v1.2.1
