### ISSUE TITLE
Job not processing images that stores in folder with space in its name

### ISSUE THREAD

**Issue by dvs39** [VirtoCommerce/vc-module-image-tools#30]

**Comment by AliveMen** [comment]
![AAI_190319_104054](https://user-images.githubusercontent.com/11813599/54588517-4d785f80-4a34-11e9-994b-7fa2e31884dc.png)

Thumbnails job works good with local storage with names with spaces. So problem in azure blob storage .

**Comment by msc2402** [comment]
I can confirm this is an issue (Virto 3.218, Image Module 3.206)

**Comment by OlegoO** [comment]
@msc2402  Which Asset provider do you use? Azure?

**Comment by OlegoO** [comment]
Fixed https://github.com/VirtoCommerce/vc-module-azureblob-assets/releases/tag/3.209.0
