### ISSUE TITLE
Thumbnails generation backend - Abstraction and Domain layer definition

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-image-tools#7]
![image.png](https://images.zenhubusercontent.com/565ffe4f638e718c995f110d/b5d365a8-4dee-44c6-b18e-3c97e5108b4a)

- Add `VirtoCommerce.ImageToolsModule.Core` project to the solution
- Define all domain model and abstraction from attached  UML
- Add comments to all Classes and methods

See example: 
https://github.com/VirtoCommerce/vc-module-subscription/tree/master/VirtoCommerce.SubscriptionModule.Core

**Comment by ksavosteev** [comment]
1. ThumbnailOption.cs - add string BackgroundColor, remove "using System";
2. SearchCriteriaBase.cs - remove this class completely, use VirtoCommerce.Domain.Commerce.Model.Search.SearchCriteriaBase, to use this class include VirtoCommerce.Domain library via Nuget
3. ThumbnailTaskSearchCriteria.cs, ThumbnailOptionSearchCriteria.cs, GenericSearchResponse.cs - refactoring - remove "using System"
4. IThumbnailOptionService.cs - decouple into two interfaces - IThumbnailOptionService.cs and IThumbnailOptionSearchService.cs (should contain SearchSettings method). Decouple the corresponding service in Data (ThumbnailOptionSearchService.cs) into ThumbnailOptionService and ThumbnailOptionSearchService accordingly
5. IThumbnailTaskSearchService.cs - fix a typo in "SerchTasks"
6. IThumbnailGenerator.cs  - fix the namespace, should be "VirtoCommerce.ImageToolsModule.Core.ThumbnailGeneration"

**Comment by andshk** [comment]
Done
