### ISSUE TITLE
Thumbnails generation backend - Persistence layer and business logic  implementation

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-image-tools#8]
![image](https://user-images.githubusercontent.com/7566324/35145232-c4b59fc2-fd0f-11e7-8cd7-9ac6142eccce.png)

- Add persistent and business logic to the exist VirtoCommerce.ImageToolsModule.Data  project

- Define persistence layer model (entities), repositories and database migrations from UML 
Example: https://github.com/VirtoCommerce/vc-module-subscription/tree/master/VirtoCommerce.SubscriptionModule.Data

- Implement DAO services  for thumbnails domain types (ThumbnailOptionSearchService, ThumbnailTaskSearchService, ThumbnailTaskService)

- Implement thumbnails generation logic implementation (ThumbnailGenerationProcessor, DefaultThumbnailGenerator) based on already existing image tools implementations. Need to use https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Core/Assets/IBlobStorageProvider.cs for reading and writing images in the storage

- write integrations tests to test all implementations (Persistent layer, DAO, Thumbnail generation logic)

**Comment by ksavosteev** [comment]
@andshk 

1. ThumbnailTaskOptionEntity should be derived from "Entity", not "AuditableEntity"
2. Add decimal Width, decimal Height, string BackgroundColor (all nullable and non required) to ThumbnailOptionEntity, fix ToModel, FromModel etc
3. Change repository OnModelCreating: remove many to many relation declaration for OptionsEntity and TaskEntity, but leave for ThumbnailTaskOptionEntity:
```
            modelBuilder.Entity<ThumbnailTaskOptionEntity>()
                .HasRequired(x => x.ThumbnailTaskEntity)
                .WithMany(t => t.ThumbnailTaskOptionEntities)
                .HasForeignKey(x=>x.ThumbnailTaskEntityId);

            modelBuilder.Entity<ThumbnailTaskOptionEntity>()
                .HasRequired(x => x.ThumbnailOptionEntity)
                .WithMany(x=>x.ThumbnailTaskOptions)
                .HasForeignKey(x=>x.ThumbnailOptionEntityId);
```

apply migration with the following commands
`Add-Migration Initial -ConnectionString "Server=(local);Database=VirtoCommerce27;Trusted_Connection=True" -ConnectionProviderName System.Data.SqlClient`
adjust Server and Database for you local connection

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-image-tools/releases
